In [3]:
import numpy as np
import tensorflow as tf
import keras
from keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from keras.utils import to_categorical

In [4]:
sentences = [
    "I love my dog",
    "I love my cat",
    "You love my dog",
    "I love a dog",
    "Do you think my dog is amazing"
    "I love mechine learning"
    "Machine learning is amazing"
]

In [5]:
my_tokenizer = Tokenizer()
my_tokenizer.fit_on_texts(sentences)

In [7]:
my_tokenizer.word_index

{'love': 1,
 'my': 2,
 'dog': 3,
 'i': 4,
 'you': 5,
 'is': 6,
 'cat': 7,
 'a': 8,
 'do': 9,
 'think': 10,
 'amazingi': 11,
 'mechine': 12,
 'learningmachine': 13,
 'learning': 14,
 'amazing': 15}

In [8]:
total_words = len(my_tokenizer.word_index) + 1
(total_words)


16

In [9]:
input_sequences = []
for i in sentences:
    token_list = my_tokenizer.texts_to_sequences([i])[0]
    for j in range(1, len(token_list)):
      n_gram_sequence = token_list[:j+1]
      input_sequences.append(n_gram_sequence)

In [10]:
input_sequences

[[4, 1],
 [4, 1, 2],
 [4, 1, 2, 3],
 [4, 1],
 [4, 1, 2],
 [4, 1, 2, 7],
 [5, 1],
 [5, 1, 2],
 [5, 1, 2, 3],
 [4, 1],
 [4, 1, 8],
 [4, 1, 8, 3],
 [9, 5],
 [9, 5, 10],
 [9, 5, 10, 2],
 [9, 5, 10, 2, 3],
 [9, 5, 10, 2, 3, 6],
 [9, 5, 10, 2, 3, 6, 11],
 [9, 5, 10, 2, 3, 6, 11, 1],
 [9, 5, 10, 2, 3, 6, 11, 1, 12],
 [9, 5, 10, 2, 3, 6, 11, 1, 12, 13],
 [9, 5, 10, 2, 3, 6, 11, 1, 12, 13, 14],
 [9, 5, 10, 2, 3, 6, 11, 1, 12, 13, 14, 6],
 [9, 5, 10, 2, 3, 6, 11, 1, 12, 13, 14, 6, 15]]

In [11]:
max_sequence_len = max([len(x) for x in input_sequences])
print(max_sequence_len)
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))


13


In [12]:
 input_sequences

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  1,  2],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  1,  2,  3],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  1,  2],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  1,  2,  7],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  1,  2],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  1,  2,  3],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  1,  8],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  1,  8,  3],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  5],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  5, 10],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  5, 10,  2],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  5, 10,  2,  3],
       [ 0,  0,  0,  0, 

In [13]:
input = input_sequences[:,:-1]
output = input_sequences[:,-1]

In [14]:
X_input = input_sequences[:,:-1]
y_output = input_sequences[:,-1]

print(X_input[0])
print(y_output[0])

[0 0 0 0 0 0 0 0 0 0 0 4]
1


In [15]:
output_c = to_categorical(output, num_classes=total_words)
output_c[1]

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
RNN = Sequential([
    layers.Embedding(total_words, 100, input_length=max_sequence_len-1),
    layers.SimpleRNN(150),
    layers.Dense(total_words, activation='softmax')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
RNN.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [18]:
RNN.fit(input,output_c,epochs=100,verbose=1)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.0000e+00 - loss: 2.7567
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2083 - loss: 2.5784
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.2500 - loss: 2.4091
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.2500 - loss: 2.2751
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.2500 - loss: 2.1988
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.2500 - loss: 2.1244
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 2.0355
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5833 - loss: 1.9483
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6667 - loss: 1.8742
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.7083 - loss: 1.8007
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.6250 - loss: 1.7180
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5833 - 

In [19]:
seed_text = __builtins__.input("Enter the text: ")
token_list = my_tokenizer.texts_to_sequences([seed_text])[0]
token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
predicted = RNN.predict(token_list)
predicted

Enter the text: Love
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 213ms/step


array([[0.00166671, 0.5148516 , 0.09136339, 0.01018122, 0.00108773,
        0.29274234, 0.00323596, 0.00563092, 0.05246353, 0.00077076,
        0.01180958, 0.00457817, 0.00351355, 0.00192464, 0.00360371,
        0.00057622]], dtype=float32)

In [20]:
predicted = np.argmax(predicted,axis=1)
print(predicted)

[1]


In [21]:
predicted_word = ""
for word, index in my_tokenizer.word_index.items():
    if index == predicted:
        predicted_word = word
        break